<a href="https://colab.research.google.com/github/SANGHATI23/genomic-evidence-reliability/blob/main/GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2_COLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/SANGHATI23/genomic-evidence-reliability/blob/main/GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2_COLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GES 3.0 — Notebook 01 Production Batch 2
## ClinVar XML Normalizer — Full Releases, 2021-04 → 2021-06

This notebook continues the validated **GES 3.0 Stage 01 production normalizer** into the second frozen longitudinal batch:

**April 2021 → June 2021**

It deliberately reuses the exact executable source of the already-validated Batch 1 notebook and applies only deterministic Batch-2 substitutions. The Stage-00 frozen manifest contract remains unchanged:

- frozen window: **2021-01 → 2026-08**
- 68 paired months
- 136 canonical model-month rows
- RCV: 37 legacy + 31 current
- VCV: 37 legacy + 31 current

### Why this wrapper exists

The goal is to prevent parser drift between production batches. Before any ClinVar source is parsed, the notebook:

1. fetches the validated Batch-1 notebook from the project repository;
2. records its SHA-256;
3. clears old outputs;
4. changes only Batch-1-specific labels, artifact names, decision keys, and the production interval;
5. verifies the Stage-00 freeze was not altered;
6. writes an expanded, audit-ready Batch-2 notebook;
7. executes the patched production cells in the current Colab kernel.

## 1. Fetch the validated Batch-1 source and construct Batch 2

This cell does **not** generically replace every occurrence of `2021-01` or `2021-03`. That would be unsafe because the Stage-00 freeze legitimately begins in 2021-01.

Only explicit Batch-1 configuration and provenance identifiers are changed.

In [1]:
from __future__ import annotations

import copy
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path

import requests

SOURCE_URL = (
    "https://raw.githubusercontent.com/SANGHATI23/"
    "genomic-evidence-reliability/main/"
    "GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH1_2021Q1_COLAB.ipynb"
)

TARGET_FILENAME = (
    "GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2_EXPANDED.ipynb"
)
TARGET_PATH = Path("/content") / TARGET_FILENAME

print("Fetching validated Batch-1 source...")
resp = requests.get(SOURCE_URL, timeout=120)
resp.raise_for_status()
raw_bytes = resp.content

SOURCE_SHA256 = hashlib.sha256(raw_bytes).hexdigest()
print("Batch-1 source bytes:", len(raw_bytes))
print("Batch-1 source SHA-256:", SOURCE_SHA256)

if len(raw_bytes) < 250_000:
    raise RuntimeError(
        "Fetched Batch-1 notebook is unexpectedly small; refusing to continue."
    )

source_nb = json.loads(raw_bytes.decode("utf-8"))
patched_nb = copy.deepcopy(source_nb)

TARGET_GITHUB_NAME = (
    "GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2_COLAB.ipynb"
)

patch_counts = {}

def replace_counted(text: str, old: str, new: str) -> str:
    n = text.count(old)
    if n:
        patch_counts[old] = patch_counts.get(old, 0) + n
        text = text.replace(old, new)
    return text

def patch_cell_source(src: str) -> str:
    s = src

    # Final "next batch" instruction must advance to Q3 before the accepted
    # Batch-2 interval is inserted elsewhere.
    s = replace_counted(
        s,
        "The next production batch should be:\n\n**2021-04 → 2021-06**",
        "The next production batch should be:\n\n**2021-07 → 2021-09**",
    )

    # Notebook / artifact provenance identifiers.
    replacements = [
        (
            "GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH1_2021Q1_COLAB.ipynb",
            TARGET_GITHUB_NAME,
        ),
        (
            "GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH1_2021Q1",
            "GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2",
        ),
        ("GES3_STAGE01_BATCH1_2021Q1", "GES3_STAGE01_BATCH2_2021Q2"),
        ("stage01_batch1_2021Q1", "stage01_batch2_2021Q2"),
        ("GES3_01_production_batch1", "GES3_01_production_batch2"),
        ("batch1_go", "batch2_go"),
        ("PRODUCTION BATCH 1", "PRODUCTION BATCH 2"),
        ("Production Batch 1", "Production Batch 2"),
        ("Batch 1", "Batch 2"),
        ("first frozen longitudinal batch", "second frozen longitudinal batch"),
        ("January 2021 → March 2021", "April 2021 → June 2021"),
        ("2021-01 → 2021-03", "2021-04 → 2021-06"),
    ]
    for old, new in replacements:
        s = replace_counted(s, old, new)

    # Executable interval: replace ONLY the Batch variables, not Stage-00.
    s = replace_counted(
        s,
        'BATCH_START_MONTH = "2021-01"',
        'BATCH_START_MONTH = "2021-04"',
    )
    s = replace_counted(
        s,
        'BATCH_END_MONTH = "2021-03"',
        'BATCH_END_MONTH = "2021-06"',
    )

    return s

for cell in patched_nb.get("cells", []):
    src = cell.get("source", "")
    if isinstance(src, list):
        src = "".join(src)

    cell["source"] = patch_cell_source(src)

    # Never carry Batch-1 execution evidence into Batch 2.
    if cell.get("cell_type") == "code":
        cell["execution_count"] = None
        cell["outputs"] = []

patched_nb.setdefault("metadata", {})
patched_nb["metadata"]["ges3_batch_patch"] = {
    "generated_utc": datetime.now(timezone.utc).isoformat(),
    "source_url": SOURCE_URL,
    "source_sha256": SOURCE_SHA256,
    "source_batch": "2021-01_to_2021-03",
    "target_batch": "2021-04_to_2021-06",
    "stage00_freeze": "2021-01_to_2026-08",
    "method": "deterministic_batch_specific_source_substitution",
}

print("\nPatch targets changed:")
for k, v in sorted(patch_counts.items()):
    print(f"  {v:>3} × {k!r}")

Fetching validated Batch-1 source...
Batch-1 source bytes: 374734
Batch-1 source SHA-256: c9ee82f07e72f65291cbc73df058360afc23593ceddab8c15f0f88173e4766cd

Patch targets changed:
    3 × '2021-01 → 2021-03'
    1 × 'BATCH_END_MONTH = "2021-03"'
    1 × 'BATCH_START_MONTH = "2021-01"'
    6 × 'Batch 1'
    1 × 'GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH1_2021Q1_COLAB.ipynb'
    1 × 'GES3_01_production_batch1'
    2 × 'GES3_STAGE01_BATCH1_2021Q1'
    1 × 'January 2021 → March 2021'
    1 × 'PRODUCTION BATCH 1'
    4 × 'Production Batch 1'
    1 × 'The next production batch should be:\n\n**2021-04 → 2021-06**'
    2 × 'batch1_go'
    1 × 'first frozen longitudinal batch'
   12 × 'stage01_batch1_2021Q1'

## 2. Hard preflight validation

These assertions are intentionally strict. If any one fails, **do not run the production parser**.

The checks confirm that:

- Batch 2 is exactly **2021-04 → 2021-06**;
- the Stage-00 lock remains **2021-01 → 2026-08**;
- the expected three-month / six-source batch structure remains intact;
- Batch-1 artifact and decision identifiers do not remain in executable code.

In [2]:
all_source = "\n".join(
    "".join(c.get("source", []))
    if isinstance(c.get("source", []), list)
    else str(c.get("source", ""))
    for c in patched_nb["cells"]
)

code_source = "\n".join(
    "".join(c.get("source", []))
    if isinstance(c.get("source", []), list)
    else str(c.get("source", ""))
    for c in patched_nb["cells"]
    if c.get("cell_type") == "code"
)

# Target batch must be exact.
assert code_source.count('BATCH_START_MONTH = "2021-04"') == 1
assert code_source.count('BATCH_END_MONTH = "2021-06"') == 1
assert 'BATCH_START_MONTH = "2021-01"' not in code_source
assert 'BATCH_END_MONTH = "2021-03"' not in code_source

# Stage-00 frozen audit invariants MUST remain untouched.
assert 'FROZEN_START_MONTH = "2021-01"' in code_source
assert 'FROZEN_END_MONTH = "2026-08"' in code_source
assert "EXPECTED_FROZEN_MONTHS = 68" in code_source
assert "EXPECTED_CANONICAL_ROWS = 136" in code_source
assert '("RCV", "legacy"): 37' in code_source
assert '("RCV", "current"): 31' in code_source
assert '("VCV", "legacy"): 37' in code_source
assert '("VCV", "current"): 31' in code_source

# Three months × two products = six production sources.
assert "EXPECTED_BATCH_MONTHS = 3" in code_source
assert "EXPECTED_BATCH_SOURCES = EXPECTED_BATCH_MONTHS * len(MODELS_TO_PROCESS)" in code_source
assert 'MODELS_TO_PROCESS = ["RCV", "VCV"]' in code_source

# Batch-2 provenance/decision names must exist.
assert "stage01_batch2_2021Q2" in code_source
assert "GES3_01_production_batch2" in code_source
assert "batch2_go" in code_source

# No executable Batch-1 provenance may survive.
for forbidden in [
    "stage01_batch1_2021Q1",
    "GES3_01_production_batch1",
    "batch1_go",
]:
    assert forbidden not in code_source, f"Unsafe leftover identifier: {forbidden}"

# Preserve production behavior.
assert 'PILOT_RECORD_LIMIT_PER_SOURCE = None' in code_source
assert "RESUME_COMPLETED_RELEASES = True" in code_source
assert "DELETE_INCOMPLETE_PARTITION_BEFORE_RETRY = True" in code_source
assert "HASH_PARQUET_SHARDS = True" in code_source

TARGET_PATH.write_text(
    json.dumps(patched_nb, ensure_ascii=False, indent=1),
    encoding="utf-8",
)

target_sha = hashlib.sha256(TARGET_PATH.read_bytes()).hexdigest()

print("BATCH-2 PREFLIGHT: PASS")
print("Target interval: 2021-04 → 2021-06")
print("Stage-00 lock: 2021-01 → 2026-08")
print("Expanded audit notebook:", TARGET_PATH)
print("Expanded notebook SHA-256:", target_sha)

BATCH-2 PREFLIGHT: PASS
Target interval: 2021-04 → 2021-06
Stage-00 lock: 2021-01 → 2026-08
Expanded audit notebook: /content/GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2_EXPANDED.ipynb
Expanded notebook SHA-256: 9259f6f4eb2d18a7bd554048f463de5e5d80c09b3bf7cd3ee75411c0ccaaa064

## 3. Execute the validated Batch-2 production normalizer

Running this cell executes the patched source cells **in their original order** in the current Colab kernel.

Expected production behavior is therefore the same as validated Batch 1:

- Stage-00 manifest lock / strict reconstruction check
- six selected sources: RCV + VCV for April, May, June 2021
- full-stream XML parsing
- compressed-stream MD5/SHA-256
- NCBI MD5 verification
- Parquet sharding
- completion markers
- structural QC
- legacy classification-semantics audit
- RCV↔SCV relationship audit
- artifact hashing
- final `batch2_go` decision

Google Drive persistence remains enabled exactly as in Batch 1.

In [3]:
from IPython import get_ipython

shell = get_ipython()
if shell is None:
    raise RuntimeError("This production runner requires an IPython/Colab kernel.")

source_code_cells = [
    (i, c)
    for i, c in enumerate(patched_nb["cells"])
    if c.get("cell_type") == "code"
]

print("Executable patched source cells:", len(source_code_cells))
print("Starting GES 3.0 Stage 01 — Production Batch 2")
print("Interval: 2021-04 → 2021-06")
print("=" * 72)

for ordinal, (source_index, cell) in enumerate(source_code_cells, start=1):
    src = cell.get("source", "")
    if isinstance(src, list):
        src = "".join(src)

    first_nonempty = next(
        (line.strip() for line in src.splitlines() if line.strip()),
        "<empty cell>",
    )

    print(
        f"\n\n######## VALIDATED SOURCE CELL "
        f"{ordinal}/{len(source_code_cells)} "
        f"(original index {source_index}) ########"
    )
    print(first_nonempty[:140])

    result = shell.run_cell(src, store_history=False)

    err = getattr(result, "error_before_exec", None) or getattr(
        result, "error_in_exec", None
    )
    if err is not None:
        raise RuntimeError(
            f"Batch-2 execution failed in validated source cell "
            f"{ordinal} (original notebook index {source_index})."
        ) from err

print("\n" + "=" * 72)
print("All patched Batch-2 source cells executed.")

Executable patched source cells: 25
Starting GES 3.0 Stage 01 — Production Batch 2
Interval: 2021-04 → 2021-06
========================================================================


######## VALIDATED SOURCE CELL 1/25 (original index 3) ########
!pip -q install lxml pyarrow pandas requests tqdm beautifulsoup4


######## VALIDATED SOURCE CELL 2/25 (original index 5) ########
from __future__ import annotations
GES 3.0 Stage 01 started: 2026-08-16T19:48:34.297127+00:00
Python: 3.12.13
lxml: 6.1.1
pyarrow: 18.1.0
pandas: 2.2.2


######## VALIDATED SOURCE CELL 3/25 (original index 7) ########
# ============================================================
RUN_PROFILE = PRODUCTION_BATCH
Batch = 2021-04 → 2021-06
Models = ['RCV', 'VCV']
Google Drive = True


######## VALIDATED SOURCE CELL 4/25 (original index 9) ########
if USE_GOOGLE_DRIVE:
Mounted at /content/drive
ROOT: /content/drive/MyDrive/GES3
Stage 00 directory: /content/drive/MyDrive/GES3/stage00
Stage 01 output: /content/drive/MyDrive/GES3/stage01


######## VALIDATED SOURCE CELL 5/25 (original index 11) ########
SESSION = requests.Session()
Loaded Stage 00 artifact: /content/drive/MyDrive/GES3/stage00/clinvar_release_manifest_canonical.csv


######## VALIDATED SOURCE CELL 6/25 (original index 13) ########
BASE = "https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/"

STAGE 00 PRODUCTION LOCK PASSED
Manifest origin: frozen_csv:/content/drive/MyDrive/GES3/stage00/clinvar_release_manifest_canonical.csv
Frozen manifest SHA-256: 8b483f722e7271d51fe9b343df3a385804f2ff48c54701a13311f6c87b246c5f
Rows: 136

  data_model format_generation   n
0        RCV           current  31
1        RCV            legacy  37
2        VCV           current  31
3        VCV            legacy  37

######## VALIDATED SOURCE CELL 7/25 (original index 15) ########
def month_between(s: pd.Series, start: str, end: str) -> pd.Series:
Batch source files: 6
Record limit: None
Batch manifest SHA-256: e729032ea47eced4b090a387a9c40881a54a983e23d5e1f47a413886e5c70e6a

,release_month,data_model,format_generation,url,ncbi_md5
0,2021-04,RCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,8521631ded8ef0da2dc8ec318a656771
1,2021-04,VCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,6158516dc0f79c023a423e52ed95ff14
2,2021-05,RCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,cb429b4e4dcf932466501781071f5a6e
3,2021-05,VCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,bbf2716f8d2e44736ed6e9e3a5be6160
4,2021-06,RCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,d4883d850b8e710982e6347cdaa26231
5,2021-06,VCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,1e4b6ab71d35b77905d13cf052ccff90

######## VALIDATED SOURCE CELL 8/25 (original index 17) ########
GERMLINE_TERMS = {
Normalized schema contract loaded.
vcv_state columns: 25
rcv_state columns: 25
scv_state columns: 23
vcv_rcv_link columns: 7


######## VALIDATED SOURCE CELL 9/25 (original index 19) ########
def localname(tag) -> str:
XML utilities loaded.


######## VALIDATED SOURCE CELL 10/25 (original index 21) ########
def parse_vcv_record(elem, release_month, source_url, source_format):


######## VALIDATED SOURCE CELL 11/25 (original index 23) ########
def infer_submission_meta(assertion):
SCV parser loaded.


######## VALIDATED SOURCE CELL 12/25 (original index 25) ########
def parse_rcv_record(elem, release_month, source_url, source_format):


######## VALIDATED SOURCE CELL 13/25 (original index 27) ########
class ShardWriter:
Parquet shard writer loaded.


######## VALIDATED SOURCE CELL 14/25 (original index 29) ########
class HashingReader:
Production streaming hash wrapper loaded.


######## VALIDATED SOURCE CELL 15/25 (original index 31) ########
def release_partition_dir(release_month, data_model, source_format):
Production full-stream release parser loaded.


######## VALIDATED SOURCE CELL 16/25 (original index 33) ########
def process_source_with_retry(row, record_limit=None):


######## VALIDATED SOURCE CELL 17/25 (original index 35) ########
run_results = []

######## SOURCE 1/6 ########

=== 2021-04 | RCV | legacy | attempt 1/3 ===
2021-04 RCV: 100,000 aggregates | 102,664 SCVs | 0.08 GiB compressed read | 941 records/s
2021-04 RCV: 200,000 aggregates | 204,673 SCVs | 0.14 GiB compressed read | 950 records/s
2021-04 RCV: 300,000 aggregates | 308,646 SCVs | 0.21 GiB compressed read | 924 records/s
2021-04 RCV: 400,000 aggregates | 415,825 SCVs | 0.32 GiB compressed read | 884 records/s
2021-04 RCV: 500,000 aggregates | 520,563 SCVs | 0.43 GiB compressed read | 849 records/s
2021-04 RCV: 600,000 aggregates | 626,367 SCVs | 0.51 GiB compressed read | 834 records/s
2021-04 RCV: 700,000 aggregates | 745,873 SCVs | 0.61 GiB compressed read | 812 records/s
2021-04 RCV: 800,000 aggregates | 864,075 SCVs | 0.71 GiB compressed read | 810 records/s
2021-04 RCV: 900,000 aggregates | 973,656 SCVs | 0.82 GiB compressed read | 793 records/s
2021-04 RCV: 1,000,000 aggregates | 1,093,675 SCVs | 0.94 GiB compressed read | 755 records/s
2021-04 RCV: 1,100,000 aggregates | 1,203,179 SCVs | 1.07 GiB compressed read | 740 records/s
2021-04 RCV: 1,200,000 aggregates | 1,352,710 SCVs | 1.20 GiB compressed read | 713 records/s
COMPLETED: 2021-04 RCV | aggregates = 1,255,840 | SCVs = 1,419,160 | MD5 = verified | minutes = 29.5

######## SOURCE 2/6 ########

=== 2021-04 | VCV | legacy | attempt 1/3 ===
2021-04 VCV: 100,000 aggregates | 106,716 SCVs | 0.07 GiB compressed read | 823 records/s
2021-04 VCV: 200,000 aggregates | 215,600 SCVs | 0.14 GiB compressed read | 781 records/s
2021-04 VCV: 300,000 aggregates | 337,435 SCVs | 0.22 GiB compressed read | 742 records/s
2021-04 VCV: 400,000 aggregates | 491,743 SCVs | 0.32 GiB compressed read | 663 records/s
2021-04 VCV: 500,000 aggregates | 627,539 SCVs | 0.43 GiB compressed read | 642 records/s
2021-04 VCV: 600,000 aggregates | 845,145 SCVs | 0.58 GiB compressed read | 576 records/s
2021-04 VCV: 700,000 aggregates | 986,424 SCVs | 0.71 GiB compressed read | 567 records/s
2021-04 VCV: 800,000 aggregates | 1,166,499 SCVs | 0.87 GiB compressed read | 535 records/s
2021-04 VCV: 900,000 aggregates | 1,405,017 SCVs | 1.09 GiB compressed read | 494 records/s
COMPLETED: 2021-04 VCV | aggregates = 914,143 | SCVs = 1,419,160 | MD5 = verified | minutes = 30.7

######## SOURCE 3/6 ########

=== 2021-05 | RCV | legacy | attempt 1/3 ===
2021-05 RCV: 100,000 aggregates | 102,512 SCVs | 0.07 GiB compressed read | 822 records/s
2021-05 RCV: 200,000 aggregates | 205,170 SCVs | 0.14 GiB compressed read | 824 records/s
2021-05 RCV: 300,000 aggregates | 308,096 SCVs | 0.21 GiB compressed read | 806 records/s
2021-05 RCV: 400,000 aggregates | 417,903 SCVs | 0.30 GiB compressed read | 779 records/s
2021-05 RCV: 500,000 aggregates | 525,993 SCVs | 0.40 GiB compressed read | 739 records/s
2021-05 RCV: 600,000 aggregates | 639,293 SCVs | 0.50 GiB compressed read | 705 records/s
2021-05 RCV: 700,000 aggregates | 777,347 SCVs | 0.61 GiB compressed read | 680 records/s
2021-05 RCV: 800,000 aggregates | 887,031 SCVs | 0.74 GiB compressed read | 670 records/s
2021-05 RCV: 900,000 aggregates | 1,001,419 SCVs | 0.85 GiB compressed read | 656 records/s
2021-05 RCV: 1,000,000 aggregates | 1,107,260 SCVs | 0.97 GiB compressed read | 647 records/s
2021-05 RCV: 1,100,000 aggregates | 1,208,602 SCVs | 1.06 GiB compressed read | 642 records/s
2021-05 RCV: 1,200,000 aggregates | 1,321,849 SCVs | 1.17 GiB compressed read | 630 records/s
COMPLETED: 2021-05 RCV | aggregates = 1,277,735 | SCVs = 1,442,676 | MD5 = verified | minutes = 34.6

######## SOURCE 4/6 ########

=== 2021-05 | VCV | legacy | attempt 1/3 ===
2021-05 VCV: 100,000 aggregates | 106,433 SCVs | 0.07 GiB compressed read | 791 records/s
2021-05 VCV: 200,000 aggregates | 214,105 SCVs | 0.13 GiB compressed read | 760 records/s
2021-05 VCV: 300,000 aggregates | 332,614 SCVs | 0.21 GiB compressed read | 726 records/s
2021-05 VCV: 400,000 aggregates | 467,527 SCVs | 0.30 GiB compressed read | 698 records/s
2021-05 VCV: 500,000 aggregates | 599,148 SCVs | 0.44 GiB compressed read | 656 records/s
2021-05 VCV: 600,000 aggregates | 883,131 SCVs | 0.63 GiB compressed read | 555 records/s
2021-05 VCV: 700,000 aggregates | 1,061,883 SCVs | 0.75 GiB compressed read | 543 records/s
2021-05 VCV: 800,000 aggregates | 1,191,081 SCVs | 0.88 GiB compressed read | 549 records/s
2021-05 VCV: 900,000 aggregates | 1,332,889 SCVs | 1.04 GiB compressed read | 544 records/s
COMPLETED: 2021-05 VCV | aggregates = 930,389 | SCVs = 1,442,676 | MD5 = verified | minutes = 29.8

######## SOURCE 5/6 ########

=== 2021-06 | RCV | legacy | attempt 1/3 ===
2021-06 RCV: 100,000 aggregates | 102,046 SCVs | 0.07 GiB compressed read | 875 records/s
2021-06 RCV: 200,000 aggregates | 204,609 SCVs | 0.14 GiB compressed read | 856 records/s
2021-06 RCV: 300,000 aggregates | 308,313 SCVs | 0.21 GiB compressed read | 835 records/s
2021-06 RCV: 400,000 aggregates | 415,184 SCVs | 0.29 GiB compressed read | 817 records/s
2021-06 RCV: 500,000 aggregates | 524,495 SCVs | 0.38 GiB compressed read | 777 records/s
2021-06 RCV: 600,000 aggregates | 638,896 SCVs | 0.49 GiB compressed read | 755 records/s
2021-06 RCV: 700,000 aggregates | 747,789 SCVs | 0.61 GiB compressed read | 735 records/s
2021-06 RCV: 800,000 aggregates | 853,870 SCVs | 0.72 GiB compressed read | 729 records/s
2021-06 RCV: 900,000 aggregates | 954,624 SCVs | 0.82 GiB compressed read | 726 records/s
2021-06 RCV: 1,000,000 aggregates | 1,071,757 SCVs | 0.92 GiB compressed read | 710 records/s
2021-06 RCV: 1,100,000 aggregates | 1,195,036 SCVs | 1.04 GiB compressed read | 701 records/s
2021-06 RCV: 1,200,000 aggregates | 1,307,107 SCVs | 1.18 GiB compressed read | 680 records/s
2021-06 RCV: 1,300,000 aggregates | 1,432,671 SCVs | 1.31 GiB compressed read | 671 records/s
COMPLETED: 2021-06 RCV | aggregates = 1,349,538 | SCVs = 1,517,833 | MD5 = verified | minutes = 33.9

######## SOURCE 6/6 ########

=== 2021-06 | VCV | legacy | attempt 1/3 ===
2021-06 VCV: 100,000 aggregates | 105,611 SCVs | 0.06 GiB compressed read | 825 records/s
2021-06 VCV: 200,000 aggregates | 213,133 SCVs | 0.13 GiB compressed read | 781 records/s
2021-06 VCV: 300,000 aggregates | 337,761 SCVs | 0.21 GiB compressed read | 734 records/s
2021-06 VCV: 400,000 aggregates | 461,819 SCVs | 0.30 GiB compressed read | 712 records/s
2021-06 VCV: 500,000 aggregates | 654,745 SCVs | 0.45 GiB compressed read | 630 records/s
2021-06 VCV: 600,000 aggregates | 819,513 SCVs | 0.56 GiB compressed read | 607 records/s
2021-06 VCV: 700,000 aggregates | 940,584 SCVs | 0.68 GiB compressed read | 609 records/s
2021-06 VCV: 800,000 aggregates | 1,110,280 SCVs | 0.85 GiB compressed read | 584 records/s
2021-06 VCV: 900,000 aggregates | 1,308,034 SCVs | 1.04 GiB compressed read | 549 records/s
COMPLETED: 2021-06 VCV | aggregates = 983,417 | SCVs = 1,517,833 | MD5 = verified | minutes = 31.4

Batch elapsed hours: 3.164

,release_month,data_model,source_format,source_url,expected_ncbi_md5,computed_stream_md5,computed_stream_sha256,compressed_bytes_read,compressed_gib_read,stream_complete,record_limit,aggregate_records,scv_records,vcv_rcv_links,elapsed_seconds,parse_error,md5_verification_status,parquet_rows,completed_utc
0,2021-04,RCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,8521631ded8ef0da2dc8ec318a656771,8521631ded8ef0da2dc8ec318a656771,955d0795ce249ee5ed54f2c4b6b8e5d6a0d4dc2f835d73...,1355128968,1.262062,True,None,1255840,1419160,0,1767.534292,None,verified,"{'vcv_state': 0, 'rcv_state': 1255840, 'scv_st...",2026-08-16T20:18:17.246683+00:00
1,2021-04,VCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,6158516dc0f79c023a423e52ed95ff14,6158516dc0f79c023a423e52ed95ff14,eeacb6f6388d778042742c2b928e693fe30e3ead88e1ca...,1191274825,1.109461,True,None,914143,1419160,1255840,1842.616885,None,verified,"{'vcv_state': 914143, 'rcv_state': 0, 'scv_sta...",2026-08-16T20:48:59.938205+00:00
2,2021-05,RCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,cb429b4e4dcf932466501781071f5a6e,cb429b4e4dcf932466501781071f5a6e,1cdc8d108b5100b99d706d044931be463124fd32d92278...,1382185562,1.287261,True,None,1277735,1442676,0,2073.267612,None,verified,"{'vcv_state': 0, 'rcv_state': 1277735, 'scv_st...",2026-08-16T21:23:33.285611+00:00
3,2021-05,VCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,bbf2716f8d2e44736ed6e9e3a5be6160,bbf2716f8d2e44736ed6e9e3a5be6160,f83a9066adc39c0643f8a7febe5d883e6f2dce00e246b5...,1213060060,1.129750,True,None,930389,1442676,1277735,1788.640050,None,verified,"{'vcv_state': 930389, 'rcv_state': 0, 'scv_sta...",2026-08-16T21:53:22.007406+00:00
4,2021-06,RCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,d4883d850b8e710982e6347cdaa26231,d4883d850b8e710982e6347cdaa26231,5df9877d8e2b9741c977a379b559f8672d679ab9431529...,1471373634,1.370323,True,None,1349538,1517833,0,2034.970827,None,verified,"{'vcv_state': 0, 'rcv_state': 1349538, 'scv_st...",2026-08-16T22:27:17.039702+00:00
5,2021-06,VCV,legacy,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,1e4b6ab71d35b77905d13cf052ccff90,1e4b6ab71d35b77905d13cf052ccff90,3dd88a48cc42d25fd97f19982b802a11f7da10f63483e1...,1299153359,1.209931,True,None,983417,1517833,1349538,1881.488730,None,verified,"{'vcv_state': 983417, 'rcv_state': 0, 'scv_sta...",2026-08-16T22:58:38.593541+00:00

######## VALIDATED SOURCE CELL 18/25 (original index 37) ########
import pyarrow.dataset as ds

,release_month,data_model,source_format,aggregate_rows,scv_rows,bad_aggregate_accessions,bad_scv_accessions,missing_release_month,missing_source_url,parser_count_match,md5_verified,completion_marker_exists
0,2021-04,RCV,legacy,1255840,1419160,0,0,0,0,True,True,True
1,2021-04,VCV,legacy,914143,1419160,0,0,0,0,True,True,True
2,2021-05,RCV,legacy,1277735,1442676,0,0,0,0,True,True,True
3,2021-05,VCV,legacy,930389,1442676,0,0,0,0,True,True,True
4,2021-06,RCV,legacy,1349538,1517833,0,0,0,0,True,True,True
5,2021-06,VCV,legacy,983417,1517833,0,0,0,0,True,True,True

ALL PRODUCTION STRUCTURAL QC PASSED: True


######## VALIDATED SOURCE CELL 19/25 (original index 39) ########
def scan_classification_counts(release_dir: Path, table_name: str):

,release_month,data_model,source_format,rows,germline_nonnull,somatic_impact_nonnull,oncogenicity_nonnull,legacy_nonnull,legacy_germline_candidate
0,2021-04,RCV,legacy,1255840,0,0,0,1255840,1223324
1,2021-04,VCV,legacy,914143,0,0,0,913483,840342
2,2021-05,RCV,legacy,1277735,0,0,0,1277735,1245219
3,2021-05,VCV,legacy,930389,0,0,0,929727,856235
4,2021-06,RCV,legacy,1349538,0,0,0,1349538,1315828
5,2021-06,VCV,legacy,983417,0,0,0,982763,906227

LEGACY CLASSIFICATION-AXIS SEPARATION PASSED: True


######## VALIDATED SOURCE CELL 20/25 (original index 41) ########
def scan_rcv_scv_relationship(release_dir: Path):

,release_month,source_format,scv_rows,scv_with_parent_rcv,unique_parent_rcv,unique_submitters,all_scvs_have_parent_rcv
0,2021-04,legacy,1419160,1419160,1255840,1868,True
1,2021-05,legacy,1442676,1442676,1277735,1898,True
2,2021-06,legacy,1517833,1517833,1349538,1929,True

RCV→SCV RELATIONSHIP QC PASSED: True


######## VALIDATED SOURCE CELL 21/25 (original index 43) ########
data_dictionary = {
{
  "vcv_state": {
    "unit": "VCV aggregate state in one ClinVar monthly release",
    "identity": [
      "release_month",
      "vcv_accession"
    ],
    "notes": "Current classification axes are separate. Legacy single classification remains explicitly legacy."
  },
  "rcv_state": {
    "unit": "RCV variant-condition aggregate state in one monthly release",
    "identity": [
      "release_month",
      "rcv_accession"
    ],
    "notes": "Primary GES 3.0 longitudinal prediction-unit foundation."
  },
  "scv_state": {
    "unit": "Submitted ClinVar assertion visible in one monthly release",
    "identity": [
      "release_month",
      "source_data_model",
      "scv_accession",
      "parent_rcv_accession",
      "parent_vcv_accession"
    ],
    "notes": "RCV-derived SCV rows preserve condition-context relationship. VCV-derived SCVs may overlap the same SCV accession and must not be naively double-counted downstream."
  },
  "vcv_rcv_link": {
    "unit": "VCV-to-RCV link visible in one monthly VCV release",
    "identity": [
      "release_month",
      "vcv_accession",
      "rcv_accession"
    ]
  },
  "classification_policy": {
    "current": "Preserve germline, somatic clinical impact, and oncogenicity as separate fields.",
    "legacy": "Preserve single classification as legacy_*; legacy_germline_candidate is only a conservative term flag, not final cohort eligibility."
  }
}


######## VALIDATED SOURCE CELL 22/25 (original index 45) ########
def sha256_file(path: Path, chunk_size=8 * 1024 * 1024):
{
  "run_utc": "2026-08-16T19:48:34.297127+00:00",
  "run_profile": "PRODUCTION_BATCH",
  "batch_start_month": "2021-04",
  "batch_end_month": "2021-06",
  "manifest_origin": "frozen_csv:/content/drive/MyDrive/GES3/stage00/clinvar_release_manifest_canonical.csv",
  "stage00_manifest_sha256": "8b483f722e7271d51fe9b343df3a385804f2ff48c54701a13311f6c87b246c5f",
  "batch_run_manifest_sha256": "e729032ea47eced4b090a387a9c40881a54a983e23d5e1f47a413886e5c70e6a",
  "record_limit_per_source": null,
  "python": "3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]",
  "platform": "Linux-6.6.122+-x86_64-with-glibc2.35",
  "pandas": "2.2.2",
  "numpy": "2.0.2",
  "pyarrow": "18.1.0",
  "lxml": "6.1.1",
  "requests": "2.32.4",
  "selected_sources": 6,
  "successful_sources": 6,
  "failed_sources": 0,
  "all_structural_qc_passed": true,
  "legacy_semantics_ok": true,
  "rcv_scv_relationship_ok": true,
  "batch_elapsed_seconds": 11388.967893362045
}

Hashed artifacts: 413

,relative_path,bytes,sha256
4,metadata/stage01_batch1_2021Q1_artifact_sha256...,60867,3086f9580f41d74e12965eedab4be2c688a1205ec0c575...
0,metadata/stage01_batch1_2021Q1_run_manifest.csv,2315,5d79a60e20841e7b407965b8744c16d7fbaf97b2e8192b...
1,metadata/stage01_batch1_2021Q1_run_manifest.sh...,105,190756ba91902f5aa9415498e89ae786ff7b92fce0d11d...
3,metadata/stage01_batch1_2021Q1_runtime_metadat...,964,ef2041a26fa75319aeda3396aea4eac58be9695f53988e...
5,metadata/stage01_batch2_2021Q2_run_manifest.csv,2315,e729032ea47eced4b090a387a9c40881a54a983e23d5e1...
6,metadata/stage01_batch2_2021Q2_run_manifest.sh...,105,eec20a3386f52b97cd72c188148c18bb9100691fa392e1...
7,metadata/stage01_batch2_2021Q2_runtime_metadat...,946,e5d665ea68133e4a8ac57ca2146d7574fe514c9aaebb4e...
2,metadata/stage01_data_dictionary.json,1412,01835d293e0c7d04eba25f0c056df65c44cfe06bb86378...
19,normalized/release_month=2021-04/data_model=RC...,1168007,b1ec2fc79391d9e6430343316eb93264f0fd6a6e49dbda...
20,normalized/release_month=2021-04/data_model=RC...,995038,1dab6157257e0f0aad03aa4f67863c24948a8406b1d420...
21,normalized/release_month=2021-04/data_model=RC...,888797,944e82e10b157dda4f34b91c644d3b51b8dabfb9764052...
22,normalized/release_month=2021-04/data_model=RC...,1036699,5ef9f4559abe0483be9cb472893dde528534c2bed6495e...
23,normalized/release_month=2021-04/data_model=RC...,1048098,e4298b7beb5929e4576f00d16e5fa070d5fbdc1ee29157...
24,normalized/release_month=2021-04/data_model=RC...,998424,d65c4a08c194ee90259905b0d301bbc8cac2a9262e0a10...
25,normalized/release_month=2021-04/data_model=RC...,1352674,6c90ed5ac83e466771175de59b0e14b14376df487e0cc1...
26,normalized/release_month=2021-04/data_model=RC...,1091068,18dd1a1b13e10974dfb2b5d6b5d4062c6fab0ecad21c4d...
27,normalized/release_month=2021-04/data_model=RC...,1208365,57b328601a01d13cfda1e06ae1cda19f4a88dfcac74262...
28,normalized/release_month=2021-04/data_model=RC...,1164847,ca81f9561206e15e980c8edc178f40579af2b313740838...
29,normalized/release_month=2021-04/data_model=RC...,1005063,1dadf1e3192e838644603c61ea991710b5c46937f12557...
30,normalized/release_month=2021-04/data_model=RC...,1107305,c6597b88052105282236eadccad873678809161c9e870f...

######## VALIDATED SOURCE CELL 23/25 (original index 47) ########
expected_source_keys = {
{
  "stage": "GES3_01_production_batch2",
  "batch": "2021-04_to_2021-06",
  "expected_sources": 6,
  "verified_completed_sources": 6,
  "failed_sources": 0,
  "all_six_completed": true,
  "structural_qc_passed": true,
  "legacy_semantics_ok": true,
  "rcv_scv_relationship_ok": true,
  "batch2_go": true
}


######## VALIDATED SOURCE CELL 24/25 (original index 49) ########
bundle_dir = Path("/content/GES3_STAGE01_BATCH2_2021Q2_METADATA")
Metadata/QC bundle: /content/GES3_STAGE01_BATCH2_2021Q2_METADATA_QC.zip
Bundle bytes: 25906


######## VALIDATED SOURCE CELL 25/25 (original index 51) ########
for result in run_results:

 2021-04 RCV legacy rcv_state

,release_month,source_url,source_format,rcv_accession,rcv_version,vcv_accession,vcv_version,variation_id,variation_name,germline_description,...,oncogenicity_review_status,legacy_classification_description,legacy_review_status,legacy_date_last_evaluated,legacy_germline_candidate,condition_names_json,condition_ids_json,gene_symbols_json,citation_ids_json,scv_count
0,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000000470,4,VCV000000441,1,441,None,None,...,None,Pathogenic,no assertion criteria provided,2007-03-01,True,"[""BLOOD GROUP--LUTHERAN NULL""]","[""OMIM:612773.0003"", ""OMIM:612773.0004"", ""OMIM...",[],"[""PubMed:17319831""]",1
1,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000003355,3,VCV000003202,1,3202,None,None,...,None,Pathogenic,no assertion criteria provided,1999-11-01,True,"[""Congenital muscular dystrophy-dystroglycanop...","[""OMIM:607440.0001"", ""OMIM:607440.0002"", ""OMIM...",[],"[""PubMed:10545611""]",1
2,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000003367,3,VCV000003212,1,3212,None,None,...,None,Pathogenic,no assertion criteria provided,2008-02-01,True,"[""Congenital muscular dystrophy-dystroglycanop...","[""OMIM:607440.0001"", ""OMIM:607440.0002"", ""OMIM...",[],"[""PubMed:18177472""]",1
3,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000004080,2,VCV000003876,1,3876,None,None,...,None,Pathogenic,no assertion criteria provided,1990-10-15,True,"[""Hexosaminidase B (paris)""]","[""MedGen:C4016989""]",[],"[""PubMed:2170400"", ""PubMed:868875""]",1
4,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000005054,3,VCV000004788,1,4788,None,None,...,None,Pathogenic,no assertion criteria provided,2001-02-01,True,"[""Autosomal recessive Dejerine-Sottas syndrome""]","[""MedGen:CN069172""]",[],"[""PubMed:11133365""]",1

 2021-04 VCV legacy vcv_state

,release_month,source_url,source_format,vcv_accession,vcv_version,variation_id,variation_type,variation_name,date_created,date_last_updated,...,oncogenicity_description,oncogenicity_review_status,legacy_classification_description,legacy_review_status,legacy_date_last_evaluated,legacy_germline_candidate,gene_symbols_json,rcv_accessions_json,citation_ids_json,scv_count
0,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000000441,1,441,Deletion,"BCAM, EX3-4DEL",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2007-03-01,True,"[""BCAM""]","[""RCV000000470""]","[""PubMed:17319831""]",1
1,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003202,1,3202,Insertion,"FKTN, L1 INS",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,1999-11-01,True,"[""FKTN""]","[""RCV000003355""]","[""PubMed:10545611""]",1
2,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003212,1,3212,Deletion,"FKTN, 473-BP DEL, NT5370",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2008-02-01,True,"[""FKTN""]","[""RCV000003367""]","[""PubMed:18177472""]",1
3,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003876,1,3876,Insertion,"HEXB, 18-BP INS",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,1990-10-15,True,"[""HEXB""]","[""RCV000004080""]","[""PubMed:2170400"", ""PubMed:868875""]",1
4,2021-04,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000004788,1,4788,Deletion,"PRX, 1-BP DEL, 2787C",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2001-02-01,True,"[""PRX""]","[""RCV000005054""]","[""PubMed:11133365""]",1

 2021-05 RCV legacy rcv_state

,release_month,source_url,source_format,rcv_accession,rcv_version,vcv_accession,vcv_version,variation_id,variation_name,germline_description,...,oncogenicity_review_status,legacy_classification_description,legacy_review_status,legacy_date_last_evaluated,legacy_germline_candidate,condition_names_json,condition_ids_json,gene_symbols_json,citation_ids_json,scv_count
0,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000000470,4,VCV000000441,1,441,None,None,...,None,Pathogenic,no assertion criteria provided,2007-03-01,True,"[""BLOOD GROUP--LUTHERAN NULL""]","[""OMIM:612773.0003"", ""OMIM:612773.0004"", ""OMIM...",[],"[""PubMed:17319831""]",1
1,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000003355,3,VCV000003202,1,3202,None,None,...,None,Pathogenic,no assertion criteria provided,1999-11-01,True,"[""Congenital muscular dystrophy-dystroglycanop...","[""OMIM:607440.0001"", ""OMIM:607440.0002"", ""OMIM...",[],"[""PubMed:10545611""]",1
2,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000003367,3,VCV000003212,1,3212,None,None,...,None,Pathogenic,no assertion criteria provided,2008-02-01,True,"[""Congenital muscular dystrophy-dystroglycanop...","[""OMIM:607440.0001"", ""OMIM:607440.0002"", ""OMIM...",[],"[""PubMed:18177472""]",1
3,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000004080,2,VCV000003876,1,3876,None,None,...,None,Pathogenic,no assertion criteria provided,1990-10-15,True,"[""Hexosaminidase B (paris)""]","[""MedGen:C4016989""]",[],"[""PubMed:2170400"", ""PubMed:868875""]",1
4,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000005054,3,VCV000004788,1,4788,None,None,...,None,Pathogenic,no assertion criteria provided,2001-02-01,True,"[""Autosomal recessive Dejerine-Sottas syndrome""]","[""MedGen:CN069172""]",[],"[""PubMed:11133365""]",1

 2021-05 VCV legacy vcv_state

,release_month,source_url,source_format,vcv_accession,vcv_version,variation_id,variation_type,variation_name,date_created,date_last_updated,...,oncogenicity_description,oncogenicity_review_status,legacy_classification_description,legacy_review_status,legacy_date_last_evaluated,legacy_germline_candidate,gene_symbols_json,rcv_accessions_json,citation_ids_json,scv_count
0,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000000441,1,441,Deletion,"BCAM, EX3-4DEL",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2007-03-01,True,"[""BCAM""]","[""RCV000000470""]","[""PubMed:17319831""]",1
1,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003202,1,3202,Insertion,"FKTN, L1 INS",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,1999-11-01,True,"[""FKTN""]","[""RCV000003355""]","[""PubMed:10545611""]",1
2,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003212,1,3212,Deletion,"FKTN, 473-BP DEL, NT5370",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2008-02-01,True,"[""FKTN""]","[""RCV000003367""]","[""PubMed:18177472""]",1
3,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003876,1,3876,Insertion,"HEXB, 18-BP INS",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,1990-10-15,True,"[""HEXB""]","[""RCV000004080""]","[""PubMed:2170400"", ""PubMed:868875""]",1
4,2021-05,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000004788,1,4788,Deletion,"PRX, 1-BP DEL, 2787C",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2001-02-01,True,"[""PRX""]","[""RCV000005054""]","[""PubMed:11133365""]",1

 2021-06 RCV legacy rcv_state

,release_month,source_url,source_format,rcv_accession,rcv_version,vcv_accession,vcv_version,variation_id,variation_name,germline_description,...,oncogenicity_review_status,legacy_classification_description,legacy_review_status,legacy_date_last_evaluated,legacy_germline_candidate,condition_names_json,condition_ids_json,gene_symbols_json,citation_ids_json,scv_count
0,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000000470,4,VCV000000441,1,441,None,None,...,None,Pathogenic,no assertion criteria provided,2007-03-01,True,"[""BLOOD GROUP--LUTHERAN NULL""]","[""OMIM:612773.0003"", ""OMIM:612773.0004"", ""OMIM...",[],"[""PubMed:17319831""]",1
1,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000003355,3,VCV000003202,1,3202,None,None,...,None,Pathogenic,no assertion criteria provided,1999-11-01,True,"[""Congenital muscular dystrophy-dystroglycanop...","[""OMIM:607440.0001"", ""OMIM:607440.0002"", ""OMIM...",[],"[""PubMed:10545611""]",1
2,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000003367,3,VCV000003212,1,3212,None,None,...,None,Pathogenic,no assertion criteria provided,2008-02-01,True,"[""Congenital muscular dystrophy-dystroglycanop...","[""OMIM:607440.0001"", ""OMIM:607440.0002"", ""OMIM...",[],"[""PubMed:18177472""]",1
3,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000004080,2,VCV000003876,1,3876,None,None,...,None,Pathogenic,no assertion criteria provided,1990-10-15,True,"[""Hexosaminidase B (paris)""]","[""MedGen:C4016989""]",[],"[""PubMed:2170400"", ""PubMed:868875""]",1
4,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/R...,legacy,RCV000005054,3,VCV000004788,1,4788,None,None,...,None,Pathogenic,no assertion criteria provided,2001-02-01,True,"[""Autosomal recessive Dejerine-Sottas syndrome""]","[""MedGen:CN069172""]",[],"[""PubMed:11133365""]",1

 2021-06 VCV legacy vcv_state

,release_month,source_url,source_format,vcv_accession,vcv_version,variation_id,variation_type,variation_name,date_created,date_last_updated,...,oncogenicity_description,oncogenicity_review_status,legacy_classification_description,legacy_review_status,legacy_date_last_evaluated,legacy_germline_candidate,gene_symbols_json,rcv_accessions_json,citation_ids_json,scv_count
0,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000000441,1,441,Deletion,"BCAM, EX3-4DEL",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2007-03-01,True,"[""BCAM""]","[""RCV000000470""]","[""PubMed:17319831""]",1
1,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003202,1,3202,Insertion,"FKTN, L1 INS",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,1999-11-01,True,"[""FKTN""]","[""RCV000003355""]","[""PubMed:10545611""]",1
2,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003212,1,3212,Deletion,"FKTN, 473-BP DEL, NT5370",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2008-02-01,True,"[""FKTN""]","[""RCV000003367""]","[""PubMed:18177472""]",1
3,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000003876,1,3876,Insertion,"HEXB, 18-BP INS",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,1990-10-15,True,"[""HEXB""]","[""RCV000004080""]","[""PubMed:2170400"", ""PubMed:868875""]",1
4,2021-06,https://ftp.ncbi.nlm.nih.gov/pub/clinvar/xml/V...,legacy,VCV000004788,1,4788,Deletion,"PRX, 1-BP DEL, 2787C",2010-12-01,2019-03-29,...,None,None,Pathogenic,None,2001-02-01,True,"[""PRX""]","[""RCV000005054""]","[""PubMed:11133365""]",1

========================================================================
All patched Batch-2 source cells executed.

## 4. Final Batch-2 acceptance check and source provenance copy

A run is accepted only if the normalizer's own final decision reports:

**`batch2_go = true`**

The expanded source used for the run is also copied into Stage-01 metadata after Drive has been mounted, so the exact executable code is retained with the production artifacts.

In [4]:
if "decision" not in globals():
    raise RuntimeError("Production decision object was not created.")

print(json.dumps(decision, indent=2))

if decision.get("batch2_go") is not True:
    raise RuntimeError(
        "Batch 2 is NOT accepted. Inspect source failures and QC before continuing."
    )

# Persist the exact expanded executable source beside Stage-01 metadata.
if "META_DIR" in globals():
    provenance_path = Path(META_DIR) / (
        "GES3_01_ClinVar_XML_Normalizer_"
        "PRODUCTION_BATCH2_2021Q2_EXPANDED_SOURCE.ipynb"
    )
    provenance_path.write_bytes(TARGET_PATH.read_bytes())

    provenance_sha = hashlib.sha256(
        provenance_path.read_bytes()
    ).hexdigest()

    sha_path = provenance_path.with_suffix(
        provenance_path.suffix + ".sha256"
    )
    sha_path.write_text(
        provenance_sha + "  " + provenance_path.name + "\n",
        encoding="utf-8",
    )

    print("Persisted executable source:", provenance_path)
    print("Executable source SHA-256:", provenance_sha)

print("\nBATCH 2 ACCEPTED ✅")
print("2021-04 → 2021-06 complete.")
print("Next Stage-01 production interval: 2021-07 → 2021-09")

{
  "stage": "GES3_01_production_batch2",
  "batch": "2021-04_to_2021-06",
  "expected_sources": 6,
  "verified_completed_sources": 6,
  "failed_sources": 0,
  "all_six_completed": true,
  "structural_qc_passed": true,
  "legacy_semantics_ok": true,
  "rcv_scv_relationship_ok": true,
  "batch2_go": true
}
Persisted executable source: /content/drive/MyDrive/GES3/stage01/metadata/GES3_01_ClinVar_XML_Normalizer_PRODUCTION_BATCH2_2021Q2_EXPANDED_SOURCE.ipynb
Executable source SHA-256: 9259f6f4eb2d18a7bd554048f463de5e5d80c09b3bf7cd3ee75411c0ccaaa064

BATCH 2 ACCEPTED ✅
2021-04 → 2021-06 complete.
Next Stage-01 production interval: 2021-07 → 2021-09