<a href="https://colab.research.google.com/github/SANGHATI23/genomic-evidence-reliability/blob/main/GES_Stage6D_Cell_6D_1B1_Authoritative_Reference_Resolution_and_Claim_Map_COLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# GES Stage 6D — Cell 6D-1B1
## Authoritative Reference Resolution + Claim-Support Map Freeze


### Why this notebook is needed
The 6D-1B0 machine audit intentionally used conservative title matching. It correctly surfaced problems, but several "mismatches" are metadata-format differences rather than bad citations.

This notebook:
- preserves all original submitted identifiers,
- distinguishes real corrections from machine false positives,
- records the known published erratum for the Amendola paper,
- creates a claim-support map for the exact role each source plays in the manuscript,

In [1]:

# Cell 1 — Setup and locate the completed 6D-1B0 audit artifacts

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import hashlib
import json
import pandas as pd

ROOT = Path("/content/drive/MyDrive/GES_RAG_Temporal_Study")
PREV = ROOT / "outputs/revision_support/stage6d_1b0_reference_audit_v1"
OUTDIR = ROOT / "outputs/revision_support/stage6d_1b1_reference_resolution_v1"
OUTDIR.mkdir(parents=True, exist_ok=True)

AUDIT = PREV / "stage6d_1b0_consolidated_reference_audit_v1.csv"
CLAIM = PREV / "stage6d_1b0_manual_claim_support_verification_sheet_v1.csv"

for p in [AUDIT, CLAIM]:
    if not p.exists():
        raise FileNotFoundError(f"Required 6D-1B0 artifact missing: {p}")

def sha256_file(path: Path, chunk_size=1024 * 1024):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()

audit = pd.read_csv(AUDIT).fillna("")
claim = pd.read_csv(CLAIM).fillna("")

if len(audit) != 17:
    raise RuntimeError(f"Expected 17 references from 6D-1B0; found {len(audit)}")

print("6D-1B0 audit SHA-256:", sha256_file(AUDIT))
print("References loaded:", len(audit))
print("Output:", OUTDIR)

Mounted at /content/drive
6D-1B0 audit SHA-256: bbf3e9181e4b9d69c68cfea4be9c98919893d120943f7012b15d6bd66a6ace50
References loaded: 17
Output: /content/drive/MyDrive/GES_RAG_Temporal_Study/outputs/revision_support/stage6d_1b1_reference_resolution_v1

In [2]:

# Cell 2 — Freeze the authoritative resolution registry

# Resolution notes are based on publisher / PubMed / official proceedings records.
# "retain" means the source itself is appropriate for the claim context.
# "correct" means the source is appropriate but bibliographic fields must change.

RESOLUTIONS = [
    {
        "ref": 1,
        "decision": "retain",
        "final_title": "ClinVar: public archive of interpretations of clinically relevant variants",
        "final_year": 2016,
        "final_venue": "Nucleic Acids Research 44(D1):D862-D868",
        "final_doi": "10.1093/nar/gkv1222",
        "final_pmid": "26582918",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/26582918/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports ClinVar as a public archive of clinically relevant variant interpretations and provenance."
    },
    {
        "ref": 2,
        "decision": "retain",
        "final_title": "Standards and guidelines for the interpretation of sequence variants: a joint consensus recommendation of the American College of Medical Genetics and Genomics and the Association for Molecular Pathology",
        "final_year": 2015,
        "final_venue": "Genetics in Medicine 17(5):405-424",
        "final_doi": "10.1038/gim.2015.30",
        "final_pmid": "25741868",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/25741868/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports the ACMG/AMP framework for sequence-variant interpretation."
    },
    {
        "ref": 3,
        "decision": "correct",
        "final_title": "Scaling resolution of variant classification differences in ClinVar between 41 clinical laboratories through an outlier approach",
        "final_year": 2018,
        "final_venue": "Human Mutation 39(11):1641-1649",
        "final_doi": "10.1002/humu.23643",
        "final_pmid": "30311378",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/30311378/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports ClinVar interlaboratory classification differences and a scalable discrepancy-resolution approach.",
        "correction_note": "Submitted DOI was correct, but submitted title and page range were wrong. Replace with the official published title and pages 1641-1649."
    },
    {
        "ref": 4,
        "decision": "correct",
        "final_title": "Prospective Study of Cancer Genetic Variants: Variation in Rate of Reclassification by Ancestry",
        "final_year": 2018,
        "final_venue": "Journal of the National Cancer Institute 110(10):1059-1066",
        "final_doi": "10.1093/jnci/djy027",
        "final_pmid": "29618041",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/29618041/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports longitudinal cancer-variant reclassification dynamics.",
        "correction_note": "Submitted DOI 10.1093/jnci/djy018 belongs to a different article. Correct DOI is 10.1093/jnci/djy027."
    },
    {
        "ref": 5,
        "decision": "retain_with_erratum_note",
        "final_title": "Performance of ACMG-AMP Variant-Interpretation Guidelines among Nine Laboratories in the Clinical Sequencing Exploratory Research Consortium",
        "final_year": 2016,
        "final_venue": "American Journal of Human Genetics 98(6):1067-1076",
        "final_doi": "10.1016/j.ajhg.2016.03.024",
        "final_pmid": "27181684",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/27181684/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports interlaboratory application/concordance of ACMG-AMP interpretation criteria.",
        "correction_note": "Published erratum exists: DOI 10.1016/j.ajhg.2016.06.001, PMID 27392081. It corrects a PS2→PS3 typo; the broad claim used in this manuscript is unaffected."
    },
    {
        "ref": 6,
        "decision": "retain",
        "final_title": "Probabilistic machine learning and artificial intelligence",
        "final_year": 2015,
        "final_venue": "Nature 521(7553):452-459",
        "final_doi": "10.1038/nature14541",
        "final_pmid": "26017444",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/26017444/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports probabilistic modelling as a framework for representing uncertainty in models and predictions."
    },
    {
        "ref": 7,
        "decision": "correct",
        "final_title": "Conformal Prediction: A Gentle Introduction",
        "final_year": 2023,
        "final_venue": "Foundations and Trends in Machine Learning 16(4):494-591",
        "final_doi": "10.1561/2200000101",
        "final_pmid": "",
        "stable_url": "https://www.nowpublishers.com/article/DownloadSummary/MAL-101",
        "claim_support": "SUPPORTED",
        "support_note": "Supports conformal prediction and distribution-free uncertainty quantification.",
        "correction_note": "The submitted title was the arXiv-style title; the DOI resolves to the published title 'Conformal Prediction: A Gentle Introduction.'"
    },
    {
        "ref": 8,
        "decision": "retain_machine_false_positive",
        "final_title": "Snorkel: Rapid Training Data Creation with Weak Supervision",
        "final_year": 2017,
        "final_venue": "Proceedings of the VLDB Endowment 11(3):269-282",
        "final_doi": "10.14778/3157794.3157797",
        "final_pmid": "29770249",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/29770249/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports programmatic weak supervision through labeling functions.",
        "correction_note": "6D-1B0 flagged Crossref's shortened metadata title 'Snorkel'; authoritative VLDB/PubMed records confirm the submitted full title and DOI."
    },
    {
        "ref": 9,
        "decision": "retain",
        "final_title": "Weakly supervised classification of aortic valve malformations using unlabeled cardiac MRI sequences",
        "final_year": 2019,
        "final_venue": "Nature Communications 10:3111",
        "final_doi": "10.1038/s41467-019-11012-3",
        "final_pmid": "31308376",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/31308376/",
        "claim_support": "SUPPORTED",
        "support_note": "Direct biomedical example of weak supervision applied to cardiac MRI classification."
    },
    {
        "ref": 10,
        "decision": "retain",
        "final_title": "What Clinicians Want: Contextualizing Explainable Machine Learning for Clinical End Use",
        "final_year": 2019,
        "final_venue": "Proceedings of Machine Learning Research 106:359-380",
        "final_doi": "",
        "final_pmid": "",
        "stable_url": "https://proceedings.mlr.press/v106/tonekaboni19a.html",
        "claim_support": "SUPPORTED",
        "support_note": "Supports clinician-centered explainability and trust considerations for clinical machine learning."
    },
    {
        "ref": 11,
        "decision": "retain",
        "final_title": "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
        "final_year": 2020,
        "final_venue": "Advances in Neural Information Processing Systems 33 (NeurIPS 2020)",
        "final_doi": "",
        "final_pmid": "",
        "stable_url": "https://proceedings.neurips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html",
        "claim_support": "SUPPORTED",
        "support_note": "Foundational RAG paper supporting the parametric-plus-retrieved-evidence architecture."
    },
    {
        "ref": 12,
        "decision": "retain",
        "final_title": "Leveraging long context in retrieval augmented language models for medical question answering",
        "final_year": 2025,
        "final_venue": "npj Digital Medicine 8:239",
        "final_doi": "10.1038/s41746-025-01651-w",
        "final_pmid": "40316710",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/40316710/",
        "claim_support": "SUPPORTED",
        "support_note": "Directly supports that context construction/retrieval ordering can materially affect medical RAG performance."
    },
    {
        "ref": 13,
        "decision": "retain",
        "final_title": "Domain-Specific Language Model Pretraining for Biomedical Natural Language Processing",
        "final_year": 2021,
        "final_venue": "ACM Transactions on Computing for Healthcare 3(1), Article 2:1-23",
        "final_doi": "10.1145/3458754",
        "final_pmid": "",
        "stable_url": "https://doi.org/10.1145/3458754",
        "claim_support": "SUPPORTED",
        "support_note": "Supports PubMed-domain pretraining and the PubMedBERT model family used for biomedical semantic retrieval."
    },
    {
        "ref": 14,
        "decision": "retain",
        "final_title": "Billion-Scale Similarity Search with GPUs",
        "final_year": 2019,
        "final_venue": "IEEE Transactions on Big Data 7(3):535-547",
        "final_doi": "10.1109/TBDATA.2019.2921572",
        "final_pmid": "",
        "stable_url": "https://ieeexplore.ieee.org/document/8733051",
        "claim_support": "SUPPORTED",
        "support_note": "Supports FAISS/GPU vector similarity-search methodology."
    },
    {
        "ref": 15,
        "decision": "retain",
        "final_title": "Scikit-learn: Machine Learning in Python",
        "final_year": 2011,
        "final_venue": "Journal of Machine Learning Research 12:2825-2830",
        "final_doi": "",
        "final_pmid": "",
        "stable_url": "https://jmlr.org/papers/v12/pedregosa11a.html",
        "claim_support": "SUPPORTED",
        "support_note": "Supports the scikit-learn software implementation citation."
    },
    {
        "ref": 16,
        "decision": "retain",
        "final_title": "Introducing GPT-4.1 in the API",
        "final_year": 2025,
        "final_venue": "OpenAI product documentation / announcement",
        "final_doi": "",
        "final_pmid": "",
        "stable_url": "https://openai.com/index/gpt-4-1/",
        "claim_support": "SUPPORTED",
        "support_note": "Official OpenAI source supporting GPT-4.1 API model-family availability and model naming."
    },
    {
        "ref": 17,
        "decision": "retain",
        "final_title": "High-performance medicine: the convergence of human and artificial intelligence",
        "final_year": 2019,
        "final_venue": "Nature Medicine 25(1):44-56",
        "final_doi": "10.1038/s41591-018-0300-7",
        "final_pmid": "30617339",
        "stable_url": "https://pubmed.ncbi.nlm.nih.gov/30617339/",
        "claim_support": "SUPPORTED",
        "support_note": "Supports human-centered clinical AI framing, including limitations and clinician/patient roles."
    },
]

resolution = pd.DataFrame(RESOLUTIONS).fillna("")

if len(resolution) != 17 or resolution["ref"].nunique() != 17:
    raise RuntimeError("Resolution registry must contain exactly 17 unique references.")

display(resolution)

,ref,decision,final_title,final_year,final_venue,final_doi,final_pmid,stable_url,claim_support,support_note,correction_note
0,1,retain,ClinVar: public archive of interpretations of ...,2016,Nucleic Acids Research 44(D1):D862-D868,10.1093/nar/gkv1222,26582918,https://pubmed.ncbi.nlm.nih.gov/26582918/,SUPPORTED,Supports ClinVar as a public archive of clinic...,
1,2,retain,Standards and guidelines for the interpretatio...,2015,Genetics in Medicine 17(5):405-424,10.1038/gim.2015.30,25741868,https://pubmed.ncbi.nlm.nih.gov/25741868/,SUPPORTED,Supports the ACMG/AMP framework for sequence-v...,
2,3,correct,Scaling resolution of variant classification d...,2018,Human Mutation 39(11):1641-1649,10.1002/humu.23643,30311378,https://pubmed.ncbi.nlm.nih.gov/30311378/,SUPPORTED,Supports ClinVar interlaboratory classificatio...,"Submitted DOI was correct, but submitted title..."
3,4,correct,Prospective Study of Cancer Genetic Variants: ...,2018,Journal of the National Cancer Institute 110(1...,10.1093/jnci/djy027,29618041,https://pubmed.ncbi.nlm.nih.gov/29618041/,SUPPORTED,Supports longitudinal cancer-variant reclassif...,Submitted DOI 10.1093/jnci/djy018 belongs to a...
4,5,retain_with_erratum_note,Performance of ACMG-AMP Variant-Interpretation...,2016,American Journal of Human Genetics 98(6):1067-...,10.1016/j.ajhg.2016.03.024,27181684,https://pubmed.ncbi.nlm.nih.gov/27181684/,SUPPORTED,Supports interlaboratory application/concordan...,Published erratum exists: DOI 10.1016/j.ajhg.2...
5,6,retain,Probabilistic machine learning and artificial ...,2015,Nature 521(7553):452-459,10.1038/nature14541,26017444,https://pubmed.ncbi.nlm.nih.gov/26017444/,SUPPORTED,Supports probabilistic modelling as a framewor...,
6,7,correct,Conformal Prediction: A Gentle Introduction,2023,Foundations and Trends in Machine Learning 16(...,10.1561/2200000101,,https://www.nowpublishers.com/article/Download...,SUPPORTED,Supports conformal prediction and distribution...,The submitted title was the arXiv-style title;...
7,8,retain_machine_false_positive,Snorkel: Rapid Training Data Creation with Wea...,2017,Proceedings of the VLDB Endowment 11(3):269-282,10.14778/3157794.3157797,29770249,https://pubmed.ncbi.nlm.nih.gov/29770249/,SUPPORTED,Supports programmatic weak supervision through...,6D-1B0 flagged Crossref's shortened metadata t...
8,9,retain,Weakly supervised classification of aortic val...,2019,Nature Communications 10:3111,10.1038/s41467-019-11012-3,31308376,https://pubmed.ncbi.nlm.nih.gov/31308376/,SUPPORTED,Direct biomedical example of weak supervision ...,
9,10,retain,What Clinicians Want: Contextualizing Explaina...,2019,Proceedings of Machine Learning Research 106:3...,,,https://proceedings.mlr.press/v106/tonekaboni1...,SUPPORTED,Supports clinician-centered explainability and...,
10,11,retain,Retrieval-Augmented Generation for Knowledge-I...,2020,Advances in Neural Information Processing Syst...,,,https://proceedings.neurips.cc/paper/2020/hash...,SUPPORTED,Foundational RAG paper supporting the parametr...,
11,12,retain,Leveraging long context in retrieval augmented...,2025,npj Digital Medicine 8:239,10.1038/s41746-025-01651-w,40316710,https://pubmed.ncbi.nlm.nih.gov/40316710/,SUPPORTED,Directly supports that context construction/re...,
12,13,retain,Domain-Specific Language Model Pretraining for...,2021,ACM Transactions on Computing for Healthcare 3...,10.1145/3458754,,https://doi.org/10.1145/3458754,SUPPORTED,Supports PubMed-domain pretraining and the Pub...,
13,14,retain,Billion-Scale Similarity Search with GPUs,2019,IEEE Transactions on Big Data 7(3):535-547,10.1109/TBDATA.2019.2921572,,https://ieeexplore.ieee.org/document/8733051,SUPPORTED,Supports FAISS/GPU vector similarity-search me...,
14,15,retain,Scikit-learn: Machine Learning in Python,2011,Journal of Machine Learning Research 12:2825-2830,,,https://jmlr.org/papers/v12/pedregosa11a.html,SUPPORTED,Supports the scikit-learn software implementat...,
15,16,retain,Introducing GPT-4.1 in the API,2025,OpenAI product documentation / announcement,,,https://openai.com/index/gpt-4-1/,SUPPORTED,Official OpenAI source supporting GPT-4.1 API ...,
16,17,retain,High-performance medicine: the convergence of ...,2019,Nature Medicine 25(1):44-56,10.1038/s41591-018-0300-7,30617339,https://pubmed.ncbi.nlm.nih.gov/30617339/,SUPPORTED,"Supports human-centered clinical AI framing, i...",

In [3]:

# Cell 3 — Join 6D-1B0 output to the authoritative registry and classify real vs false-positive flags

joined = audit.merge(
    resolution,
    on="ref",
    how="left",
    validate="one_to_one",
    suffixes=("_submitted", "_resolved"),
)

if joined["decision"].eq("").any():
    raise RuntimeError("At least one 6D-1B0 reference lacks a resolution.")

joined["requires_bibliography_change"] = joined["decision"].isin(
    ["correct", "retain_with_erratum_note"]
)

joined["machine_flag_resolution"] = joined.apply(
    lambda r: (
        "REAL_BIBLIOGRAPHIC_CORRECTION"
        if r["decision"] == "correct"
        else
        "ERRATUM_REVIEWED_SOURCE_RETAINED"
        if r["decision"] == "retain_with_erratum_note"
        else
        "MACHINE_FALSE_POSITIVE_SOURCE_RETAINED"
        if r["decision"] == "retain_machine_false_positive"
        else
        "SOURCE_RETAINED"
    ),
    axis=1,
)

display(joined[
    [
        "ref", "title", "doi_submitted", "doi_title_mismatch_flag",
        "decision", "machine_flag_resolution", "final_title", "final_doi",
        "final_pmid", "claim_support"
    ]
])

,ref,title,doi_submitted,doi_title_mismatch_flag,decision,machine_flag_resolution,final_title,final_doi,final_pmid,claim_support
0,1,ClinVar: public archive of interpretations of ...,10.1093/nar/gkv1222,False,retain,SOURCE_RETAINED,ClinVar: public archive of interpretations of ...,10.1093/nar/gkv1222,26582918,SUPPORTED
1,2,Standards and guidelines for the interpretatio...,10.1038/gim.2015.30,False,retain,SOURCE_RETAINED,Standards and guidelines for the interpretatio...,10.1038/gim.2015.30,25741868,SUPPORTED
2,3,Scaling resolution of variant classification d...,10.1002/humu.23643,True,correct,REAL_BIBLIOGRAPHIC_CORRECTION,Scaling resolution of variant classification d...,10.1002/humu.23643,30311378,SUPPORTED
3,4,Prospective study of cancer genetic variants: ...,10.1093/jnci/djy018,True,correct,REAL_BIBLIOGRAPHIC_CORRECTION,Prospective Study of Cancer Genetic Variants: ...,10.1093/jnci/djy027,29618041,SUPPORTED
4,5,Performance of ACMG-AMP variant-interpretation...,10.1016/j.ajhg.2016.03.024,False,retain_with_erratum_note,ERRATUM_REVIEWED_SOURCE_RETAINED,Performance of ACMG-AMP Variant-Interpretation...,10.1016/j.ajhg.2016.03.024,27181684,SUPPORTED
5,6,Probabilistic machine learning and artificial ...,10.1038/nature14541,False,retain,SOURCE_RETAINED,Probabilistic machine learning and artificial ...,10.1038/nature14541,26017444,SUPPORTED
6,7,A gentle introduction to conformal prediction ...,10.1561/2200000101,True,correct,REAL_BIBLIOGRAPHIC_CORRECTION,Conformal Prediction: A Gentle Introduction,10.1561/2200000101,,SUPPORTED
7,8,Snorkel: rapid training data creation with wea...,10.14778/3157794.3157797,True,retain_machine_false_positive,MACHINE_FALSE_POSITIVE_SOURCE_RETAINED,Snorkel: Rapid Training Data Creation with Wea...,10.14778/3157794.3157797,29770249,SUPPORTED
8,9,Weakly supervised classification of aortic val...,10.1038/s41467-019-11012-3,False,retain,SOURCE_RETAINED,Weakly supervised classification of aortic val...,10.1038/s41467-019-11012-3,31308376,SUPPORTED
9,10,What clinicians want: contextualizing explaina...,,False,retain,SOURCE_RETAINED,What Clinicians Want: Contextualizing Explaina...,,,SUPPORTED
10,11,Retrieval-augmented generation for knowledge-i...,,False,retain,SOURCE_RETAINED,Retrieval-Augmented Generation for Knowledge-I...,,,SUPPORTED
11,12,Leveraging long context in retrieval augmented...,10.1038/s41746-025-01651-w,False,retain,SOURCE_RETAINED,Leveraging long context in retrieval augmented...,10.1038/s41746-025-01651-w,40316710,SUPPORTED
12,13,Domain-specific language model pretraining for...,10.1145/3458754,False,retain,SOURCE_RETAINED,Domain-Specific Language Model Pretraining for...,10.1145/3458754,,SUPPORTED
13,14,Billion-scale similarity search with GPUs,10.1109/TBDATA.2019.2921572,False,retain,SOURCE_RETAINED,Billion-Scale Similarity Search with GPUs,10.1109/TBDATA.2019.2921572,,SUPPORTED
14,15,Scikit-learn: machine learning in Python,,False,retain,SOURCE_RETAINED,Scikit-learn: Machine Learning in Python,,,SUPPORTED
15,16,Introducing GPT-4.1 in the API,,False,retain,SOURCE_RETAINED,Introducing GPT-4.1 in the API,,,SUPPORTED
16,17,High-performance medicine: the convergence of ...,10.1038/s41591-018-0300-7,False,retain,SOURCE_RETAINED,High-performance medicine: the convergence of ...,10.1038/s41591-018-0300-7,30617339,SUPPORTED

In [4]:

# Cell 4 — Fail closed on the known high-priority corrections

r3 = resolution.loc[resolution["ref"] == 3].iloc[0]
r4 = resolution.loc[resolution["ref"] == 4].iloc[0]
r5 = resolution.loc[resolution["ref"] == 5].iloc[0]
r7 = resolution.loc[resolution["ref"] == 7].iloc[0]
r8 = resolution.loc[resolution["ref"] == 8].iloc[0]

assert r3["final_doi"] == "10.1002/humu.23643"
assert "41 clinical laboratories" in r3["final_title"]
assert "1641-1649" in r3["final_venue"]

assert r4["final_doi"] == "10.1093/jnci/djy027"
assert r4["final_pmid"] == "29618041"

assert "10.1016/j.ajhg.2016.06.001" in r5.get("correction_note", "")

assert r7["final_title"] == "Conformal Prediction: A Gentle Introduction"
assert r7["final_doi"] == "10.1561/2200000101"

assert r8["final_doi"] == "10.14778/3157794.3157797"

print("PASS — known high-priority bibliographic issues resolved explicitly.")

PASS — known high-priority bibliographic issues resolved explicitly.

In [5]:

# Cell 5 — Generate final corrected bibliography lines

def id_suffix(row):
    parts = []
    if str(row["final_doi"]).strip():
        parts.append(f"https://doi.org/{row['final_doi']}")
    if str(row["final_pmid"]).strip():
        parts.append(f"PMID: {row['final_pmid']}")
    if not parts and str(row["stable_url"]).strip():
        parts.append(row["stable_url"])
    return ". ".join(parts)

bibliography_lines = []
for _, r in resolution.sort_values("ref").iterrows():
    line = (
        f"{int(r['ref'])}. {r['final_title']}. "
        f"{r['final_venue']} ({int(r['final_year'])})."
    )
    suffix = id_suffix(r)
    if suffix:
        line += f" {suffix}"
    bibliography_lines.append(line)

bib_txt = OUTDIR / "stage6d_1b1_corrected_bibliography_v1.txt"
bib_txt.write_text("\n".join(bibliography_lines) + "\n", encoding="utf-8")

for line in bibliography_lines:
    print(line)

1. ClinVar: public archive of interpretations of clinically relevant variants. Nucleic Acids Research 44(D1):D862-D868 (2016). https://doi.org/10.1093/nar/gkv1222. PMID: 26582918
2. Standards and guidelines for the interpretation of sequence variants: a joint consensus recommendation of the American College of Medical Genetics and Genomics and the Association for Molecular Pathology. Genetics in Medicine 17(5):405-424 (2015). https://doi.org/10.1038/gim.2015.30. PMID: 25741868
3. Scaling resolution of variant classification differences in ClinVar between 41 clinical laboratories through an outlier approach. Human Mutation 39(11):1641-1649 (2018). https://doi.org/10.1002/humu.23643. PMID: 30311378
4. Prospective Study of Cancer Genetic Variants: Variation in Rate of Reclassification by Ancestry. Journal of the National Cancer Institute 110(10):1059-1066 (2018). https://doi.org/10.1093/jnci/djy027. PMID: 29618041
5. Performance of ACMG-AMP Variant-Interpretation Guidelines among Nine Laboratories in the Clinical Sequencing Exploratory Research Consortium. American Journal of Human Genetics 98(6):1067-1076 (2016). https://doi.org/10.1016/j.ajhg.2016.03.024. PMID: 27181684
6. Probabilistic machine learning and artificial intelligence. Nature 521(7553):452-459 (2015). https://doi.org/10.1038/nature14541. PMID: 26017444
7. Conformal Prediction: A Gentle Introduction. Foundations and Trends in Machine Learning 16(4):494-591 (2023). https://doi.org/10.1561/2200000101
8. Snorkel: Rapid Training Data Creation with Weak Supervision. Proceedings of the VLDB Endowment 11(3):269-282 (2017). https://doi.org/10.14778/3157794.3157797. PMID: 29770249
9. Weakly supervised classification of aortic valve malformations using unlabeled cardiac MRI sequences. Nature Communications 10:3111 (2019). https://doi.org/10.1038/s41467-019-11012-3. PMID: 31308376
10. What Clinicians Want: Contextualizing Explainable Machine Learning for Clinical End Use. Proceedings of Machine Learning Research 106:359-380 (2019). https://proceedings.mlr.press/v106/tonekaboni19a.html
11. Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks. Advances in Neural Information Processing Systems 33 (NeurIPS 2020) (2020). https://proceedings.neurips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html
12. Leveraging long context in retrieval augmented language models for medical question answering. npj Digital Medicine 8:239 (2025). https://doi.org/10.1038/s41746-025-01651-w. PMID: 40316710
13. Domain-Specific Language Model Pretraining for Biomedical Natural Language Processing. ACM Transactions on Computing for Healthcare 3(1), Article 2:1-23 (2021). https://doi.org/10.1145/3458754
14. Billion-Scale Similarity Search with GPUs. IEEE Transactions on Big Data 7(3):535-547 (2019). https://doi.org/10.1109/TBDATA.2019.2921572
15. Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research 12:2825-2830 (2011). https://jmlr.org/papers/v12/pedregosa11a.html
16. Introducing GPT-4.1 in the API. OpenAI product documentation / announcement (2025). https://openai.com/index/gpt-4-1/
17. High-performance medicine: the convergence of human and artificial intelligence. Nature Medicine 25(1):44-56 (2019). https://doi.org/10.1038/s41591-018-0300-7. PMID: 30617339

In [6]:

# Cell 6 — Create the final claim-support verification map

support_map = resolution[
    [
        "ref", "final_title", "final_doi", "final_pmid", "stable_url",
        "claim_support", "support_note", "decision"
    ]
].copy()

# Map the broad manuscript use from 6D-1B0 so the editorial package shows
# both bibliographic authenticity and claim relevance.
submitted_claims = claim[["ref", "claim_context"]].copy()
support_map = support_map.merge(
    submitted_claims,
    on="ref",
    how="left",
    validate="one_to_one"
)

support_map["source_real_and_traceable"] = True
support_map["relevant_to_cited_claim"] = support_map["claim_support"].eq("SUPPORTED")
support_map["retain_replace_remove"] = "RETAIN"
support_map.loc[support_map["decision"] == "correct", "retain_replace_remove"] = "RETAIN_WITH_CORRECTED_BIBLIOGRAPHY"
support_map.loc[support_map["decision"] == "retain_with_erratum_note", "retain_replace_remove"] = "RETAIN_ERRATUM_REVIEWED"

if not support_map["source_real_and_traceable"].all():
    raise RuntimeError("Every retained source must be traceable.")
if not support_map["relevant_to_cited_claim"].all():
    raise RuntimeError("Every retained source must support its mapped manuscript claim.")

support_path = OUTDIR / "stage6d_1b1_final_claim_support_map_v1.csv"
support_map.to_csv(support_path, index=False)

display(support_map)

,ref,final_title,final_doi,final_pmid,stable_url,claim_support,support_note,decision,claim_context,source_real_and_traceable,relevant_to_cited_claim,retain_replace_remove
0,1,ClinVar: public archive of interpretations of ...,10.1093/nar/gkv1222,26582918,https://pubmed.ncbi.nlm.nih.gov/26582918/,SUPPORTED,Supports ClinVar as a public archive of clinic...,retain,ClinVar archive structure and clinically inter...,True,True,RETAIN
1,2,Standards and guidelines for the interpretatio...,10.1038/gim.2015.30,25741868,https://pubmed.ncbi.nlm.nih.gov/25741868/,SUPPORTED,Supports the ACMG/AMP framework for sequence-v...,retain,ACMG/AMP sequence-variant interpretation frame...,True,True,RETAIN
2,3,Scaling resolution of variant classification d...,10.1002/humu.23643,30311378,https://pubmed.ncbi.nlm.nih.gov/30311378/,SUPPORTED,Supports ClinVar interlaboratory classificatio...,correct,ClinVar classification differences/disagreemen...,True,True,RETAIN_WITH_CORRECTED_BIBLIOGRAPHY
3,4,Prospective Study of Cancer Genetic Variants: ...,10.1093/jnci/djy027,29618041,https://pubmed.ncbi.nlm.nih.gov/29618041/,SUPPORTED,Supports longitudinal cancer-variant reclassif...,correct,Cancer-variant reclassification dynamics,True,True,RETAIN_WITH_CORRECTED_BIBLIOGRAPHY
4,5,Performance of ACMG-AMP Variant-Interpretation...,10.1016/j.ajhg.2016.03.024,27181684,https://pubmed.ncbi.nlm.nih.gov/27181684/,SUPPORTED,Supports interlaboratory application/concordan...,retain_with_erratum_note,Interlaboratory variant-interpretation concord...,True,True,RETAIN_ERRATUM_REVIEWED
5,6,Probabilistic machine learning and artificial ...,10.1038/nature14541,26017444,https://pubmed.ncbi.nlm.nih.gov/26017444/,SUPPORTED,Supports probabilistic modelling as a framewor...,retain,Probabilistic/model uncertainty,True,True,RETAIN
6,7,Conformal Prediction: A Gentle Introduction,10.1561/2200000101,,https://www.nowpublishers.com/article/Download...,SUPPORTED,Supports conformal prediction and distribution...,correct,Conformal prediction and uncertainty quantific...,True,True,RETAIN_WITH_CORRECTED_BIBLIOGRAPHY
7,8,Snorkel: Rapid Training Data Creation with Wea...,10.14778/3157794.3157797,29770249,https://pubmed.ncbi.nlm.nih.gov/29770249/,SUPPORTED,Supports programmatic weak supervision through...,retain_machine_false_positive,Weak supervision/programmatic labeling,True,True,RETAIN
8,9,Weakly supervised classification of aortic val...,10.1038/s41467-019-11012-3,31308376,https://pubmed.ncbi.nlm.nih.gov/31308376/,SUPPORTED,Direct biomedical example of weak supervision ...,retain,Biomedical application of weak supervision,True,True,RETAIN
9,10,What Clinicians Want: Contextualizing Explaina...,,,https://proceedings.mlr.press/v106/tonekaboni1...,SUPPORTED,Supports clinician-centered explainability and...,retain,Clinician-centered explainability / trustworth...,True,True,RETAIN
10,11,Retrieval-Augmented Generation for Knowledge-I...,,,https://proceedings.neurips.cc/paper/2020/hash...,SUPPORTED,Foundational RAG paper supporting the parametr...,retain,RAG architecture and retrieval-augmented gener...,True,True,RETAIN
11,12,Leveraging long context in retrieval augmented...,10.1038/s41746-025-01651-w,40316710,https://pubmed.ncbi.nlm.nih.gov/40316710/,SUPPORTED,Directly supports that context construction/re...,retain,Medical RAG and context/retrieval effects,True,True,RETAIN
12,13,Domain-Specific Language Model Pretraining for...,10.1145/3458754,,https://doi.org/10.1145/3458754,SUPPORTED,Supports PubMed-domain pretraining and the Pub...,retain,Biomedical-domain language-model pretraining /...,True,True,RETAIN
13,14,Billion-Scale Similarity Search with GPUs,10.1109/TBDATA.2019.2921572,,https://ieeexplore.ieee.org/document/8733051,SUPPORTED,Supports FAISS/GPU vector similarity-search me...,retain,FAISS / dense-vector similarity search,True,True,RETAIN
14,15,Scikit-learn: Machine Learning in Python,,,https://jmlr.org/papers/v12/pedregosa11a.html,SUPPORTED,Supports the scikit-learn software implementat...,retain,scikit-learn implementation,True,True,RETAIN
15,16,Introducing GPT-4.1 in the API,,,https://openai.com/index/gpt-4-1/,SUPPORTED,Official OpenAI source supporting GPT-4.1 API ...,retain,Pinned GPT-4.1 model family/API documentation,True,True,RETAIN
16,17,High-performance medicine: the convergence of ...,10.1038/s41591-018-0300-7,30617339,https://pubmed.ncbi.nlm.nih.gov/30617339/,SUPPORTED,"Supports human-centered clinical AI framing, i...",retain,Human-centered/trustworthy clinical AI framing,True,True,RETAIN

In [7]:

# Cell 7 — Create explicit correction log for manuscript editing

correction_log = resolution[
    resolution["decision"].isin(["correct", "retain_with_erratum_note", "retain_machine_false_positive"])
][
    ["ref", "decision", "final_title", "final_doi", "final_pmid", "correction_note"]
].copy()

correction_path = OUTDIR / "stage6d_1b1_bibliographic_correction_log_v1.csv"
correction_log.to_csv(correction_path, index=False)

print("Bibliographic correction/review items:")
display(correction_log)

print("\nInterpretation:")
print("- Ref 3: source retained; title/page range corrected.")
print("- Ref 4: source retained; DOI and PMID corrected.")
print("- Ref 5: source retained; published erratum reviewed and noted.")
print("- Ref 7: source retained; published title aligned to DOI.")
print("- Ref 8: source retained; 6D-1B0 mismatch was a Crossref short-title false positive.")

Bibliographic correction/review items:

,ref,decision,final_title,final_doi,final_pmid,correction_note
2,3,correct,Scaling resolution of variant classification d...,10.1002/humu.23643,30311378,"Submitted DOI was correct, but submitted title..."
3,4,correct,Prospective Study of Cancer Genetic Variants: ...,10.1093/jnci/djy027,29618041,Submitted DOI 10.1093/jnci/djy018 belongs to a...
4,5,retain_with_erratum_note,Performance of ACMG-AMP Variant-Interpretation...,10.1016/j.ajhg.2016.03.024,27181684,Published erratum exists: DOI 10.1016/j.ajhg.2...
6,7,correct,Conformal Prediction: A Gentle Introduction,10.1561/2200000101,,The submitted title was the arXiv-style title;...
7,8,retain_machine_false_positive,Snorkel: Rapid Training Data Creation with Wea...,10.14778/3157794.3157797,29770249,6D-1B0 flagged Crossref's shortened metadata t...

Interpretation:
- Ref 3: source retained; title/page range corrected.
- Ref 4: source retained; DOI and PMID corrected.
- Ref 5: source retained; published erratum reviewed and noted.
- Ref 7: source retained; published title aligned to DOI.
- Ref 8: source retained; 6D-1B0 mismatch was a Crossref short-title false positive.

In [8]:

# Cell 8 — Save final resolution table and reviewer-facing response text

resolution_path = OUTDIR / "stage6d_1b1_authoritative_reference_resolution_v1.csv"
resolution.to_csv(resolution_path, index=False)

reviewer_text = """
Comment 7 — Reference verification

Response:
All 17 references retained in the revised manuscript were re-verified against
authoritative records including PubMed, publisher pages, and official conference/
proceedings pages as applicable. Bibliographic discrepancies identified during the
audit were corrected rather than silently retained. Specifically, the Harrison et al.
ClinVar paper was updated to its official published title and page range; the Slavin
et al. reclassification paper DOI was corrected to 10.1093/jnci/djy027; the
Angelopoulos and Bates citation was aligned to the published title associated with
DOI 10.1561/2200000101; and the full Snorkel title was retained after confirming
that the earlier machine flag reflected shortened Crossref metadata. A published
erratum for Amendola et al. (10.1016/j.ajhg.2016.06.001) was reviewed; it corrects
a PS2-to-PS3 typographical error and does not alter the broad interlaboratory/
guideline-performance claim for which the source is cited.

A reference-level verification table records the final identifier, stable source,
claim role, and retain/correct decision for each source.
""".strip()

response_txt = OUTDIR / "stage6d_1b1_reviewer_comment7_response_draft_v1.txt"
response_txt.write_text(reviewer_text + "\n", encoding="utf-8")

print(reviewer_text)

Comment 7 — Reference verification

Response:
All 17 references retained in the revised manuscript were re-verified against
authoritative records including PubMed, publisher pages, and official conference/
proceedings pages as applicable. Bibliographic discrepancies identified during the
audit were corrected rather than silently retained. Specifically, the Harrison et al.
ClinVar paper was updated to its official published title and page range; the Slavin
et al. reclassification paper DOI was corrected to 10.1093/jnci/djy027; the
Angelopoulos and Bates citation was aligned to the published title associated with
DOI 10.1561/2200000101; and the full Snorkel title was retained after confirming
that the earlier machine flag reflected shortened Crossref metadata. A published
erratum for Amendola et al. (10.1016/j.ajhg.2016.06.001) was reviewed; it corrects
a PS2-to-PS3 typographical error and does not alter the broad interlaboratory/
guideline-performance claim for which the source is cited.

A reference-level verification table records the final identifier, stable source,
claim role, and retain/correct decision for each source.

In [9]:

# Cell 9 — Freeze manifest and SHA-256 sidecars

artifacts = [
    resolution_path,
    support_path,
    correction_path,
    bib_txt,
    response_txt,
]

manifest_rows = []
for p in artifacts:
    manifest_rows.append({
        "artifact": str(p),
        "bytes": Path(p).stat().st_size,
        "sha256": sha256_file(Path(p)),
    })

manifest = pd.DataFrame(manifest_rows)
manifest_path = OUTDIR / "stage6d_1b1_manifest_v1.csv"
manifest.to_csv(manifest_path, index=False)

for p in artifacts + [manifest_path]:
    p = Path(p)
    p.with_name(p.name + ".sha256").write_text(
        f"{sha256_file(p)}  {p.name}\n",
        encoding="utf-8"
    )

display(manifest)
print("Manifest:", manifest_path)

,artifact,bytes,sha256
0,/content/drive/MyDrive/GES_RAG_Temporal_Study/...,6115,44576af9b858455854d9c5e78a723f1ade657ce02f4797...
1,/content/drive/MyDrive/GES_RAG_Temporal_Study/...,5863,642460ce45379f733261a0d7bf1c470aa23edd1812bdf7...
2,/content/drive/MyDrive/GES_RAG_Temporal_Study/...,1441,4c058d03b0f982b33fb89eae6ec669cdc0e654c0a941cf...
3,/content/drive/MyDrive/GES_RAG_Temporal_Study/...,3294,0ee1c36da193a734d99cae8b181b78be7c7e803ac9e1a0...
4,/content/drive/MyDrive/GES_RAG_Temporal_Study/...,1144,0be6c3b56bc878183e7c4c216ad354e045d3ce711f74a5...

Manifest: /content/drive/MyDrive/GES_RAG_Temporal_Study/outputs/revision_support/stage6d_1b1_reference_resolution_v1/stage6d_1b1_manifest_v1.csv

In [10]:

# Cell 10 — Final PASS gate

n = len(resolution)
n_supported = int((resolution["claim_support"] == "SUPPORTED").sum())
n_corrected = int((resolution["decision"] == "correct").sum())
n_erratum = int((resolution["decision"] == "retain_with_erratum_note").sum())
n_false_positive = int((resolution["decision"] == "retain_machine_false_positive").sum())

print("FINAL REFERENCE RESOLUTION")
print("--------------------------")
print("References resolved:", n)
print("Claim-support mappings supported:", n_supported)
print("Bibliographic corrections:", n_corrected)
print("Erratum-reviewed retained sources:", n_erratum)
print("Machine false-positive resolutions:", n_false_positive)

if n != 17:
    raise RuntimeError("Expected 17 resolved references.")
if n_supported != 17:
    raise RuntimeError("Every retained reference must have a supported claim map.")

print("\nPASS — 6D-1B1 authoritative reference-resolution package frozen.")
print("Next: Stage 6D-1C0 final Springer revision evidence/reproducibility package.")

FINAL REFERENCE RESOLUTION
--------------------------
References resolved: 17
Claim-support mappings supported: 17
Bibliographic corrections: 3
Erratum-reviewed retained sources: 1
Machine false-positive resolutions: 1

PASS — 6D-1B1 authoritative reference-resolution package frozen.
Next: Stage 6D-1C0 final Springer revision evidence/reproducibility package.